algoritmo "Ex.22"
// Função : Receba 2 inteiros e mostre seus valores em ordem crescente
// Autor : Raphael Dinelli
// Data : 19/02/2016
// Seção de Declarações 
var
         a, b : inteiro
inicio
         leia(a)
         leia(b)
         se (a < b) entao
            escreva(a)
            escreva(b)
         senao
            escreva(b)
            escreva(a)
         fimse
fimalgoritmo
