algoritmo "Ex.31"
// Função : Calcule e mostre o quadrado dos números entre 10 e 150.
// Autor : Raphael Dinelli
// Data : 19/02/2016
// Seção de Declarações 
var
         numero : inteiro
inicio
         escreval("Quadrado dos números entre 10 e 150: ")
         numero := 10
         enquanto numero <= 150 faca
            escreval("Número: ", numero, " | Quadrado: ", (numero^2))
            numero := numero+1


         fimenquanto


fimalgoritmo
