Algoritmo "cauculaVolumeParalelepipedo"
// Descrição   : Receba os valores do comprimento,
//largura e altura de um paralelepípedo. Calcule e mostre seu volume.
// Autor(a)    : Raphael Dinelli
// Data atual  : 20/02/2016
Var
   altura, largura, comprimento : inteiro

Inicio
   leia(altura)

   leia(largura)

   leia(comprimento)
   escreval("Volume do paralelepipedo: ", (altura*largura*comprimento), " cm3")



Fimalgoritmo